spring.application.name=odoru-stats-service
server.port=8084

odoru.member-service.url=http://${MEMBER_SERVICE_HOST:localhost}:8080
odoru.lesson-service.url=http://${LESSON_SERVICE_HOST:localhost}:8081
odoru.competition-service.url=http://${COMPETITION_SERVICE_HOST:localhost}:8082
odoru.badge-service.url=http://${BADGE_SERVICE_HOST:localhost}:8083

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8080}/realms/odoru/protocol/openid-connect/certs

