services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  member-service:
    build:
      context: ./odoru-member-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/odoru_member_db
    depends_on:
      - mongodb

  lesson-service:
    build:
      context: ./odoru-lesson-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/odoru_lesson_db
      - MEMBER_SERVICE_HOST=member-service
    depends_on:
      - mongodb
      - member-service

volumes:
  mongo-data:

