spring.application.name=odoru-badge-service
server.port=8083

spring.data.mongodb.uri=mongodb://${MONGODB_HOST:localhost}:27017/odoru_badge_db
spring.data.mongodb.auto-index-creation=true

odoru.member-service.url=http://${MEMBER_SERVICE_HOST:localhost}:8080
odoru.lesson-service.url=http://${LESSON_SERVICE_HOST:localhost}:8081

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:9090}/realms/odoru/protocol/openid-connect/certs
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
