spring.application.name=odoru-member-service
server.port=8080

spring.data.mongodb.uri=mongodb://${MONGODB_HOST:localhost}:27017/odoru_member_db
spring.data.mongodb.auto-index-creation=true

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:9090}/realms/odoru/protocol/openid-connect/certs

